version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/gui"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 5
    groups:
      npm-production:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      npm-development:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 5
    groups:
      pip-production:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      pip-development:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
