/**
 * Symplectic encoding of Pauli strings over GF(2) and span-membership test.
 *
 * Each n-qubit Pauli (up to sign) maps to a 2n-bit vector. The first n bits
 * are X-components, the next n are Z-components:
 *   I → (0, 0),  X → (1, 0),  Z → (0, 1),  Y → (1, 1).
 *
 * Stabilizer flows (correlation surfaces) form an Abelian subgroup of the
 * port Pauli group under element-wise multiplication. Ignoring phases, that
 * operation is exactly XOR on the symplectic vectors, so checking whether a
 * candidate flow lies in the group generated by a given set reduces to a
 * linear-algebra question over GF(2): is the candidate vector in the row
 * span of the generator matrix?
 */

export type SymplecticVec = number[]; // length 2n, entries in {0, 1}

export function pauliToSymplectic(pauli: string): SymplecticVec {
  const n = pauli.length;
  const v = new Array<number>(2 * n).fill(0);
  for (let i = 0; i < n; i++) {
    const c = pauli[i];
    if (c === "X" || c === "Y") v[i] = 1;
    if (c === "Z" || c === "Y") v[i + n] = 1;
  }
  return v;
}

/** Is `query` in the GF(2) row span of `basis`? */
export function isInSpanGF2(basis: SymplecticVec[], query: SymplecticVec): boolean {
  if (basis.length === 0) return query.every((x) => x === 0);
  const width = query.length;
  const rows = basis.map((r) => r.slice());
  let pivotRow = 0;
  const pivotCols: number[] = [];

  for (let col = 0; col < width && pivotRow < rows.length; col++) {
    let pr = -1;
    for (let r = pivotRow; r < rows.length; r++) {
      if (rows[r][col] === 1) {
        pr = r;
        break;
      }
    }
    if (pr === -1) continue;
    if (pr !== pivotRow) {
      const tmp = rows[pivotRow];
      rows[pivotRow] = rows[pr];
      rows[pr] = tmp;
    }
    for (let r = 0; r < rows.length; r++) {
      if (r !== pivotRow && rows[r][col] === 1) {
        for (let c = col; c < width; c++) rows[r][c] ^= rows[pivotRow][c];
      }
    }
    pivotCols.push(col);
    pivotRow++;
  }

  const q = query.slice();
  for (let i = 0; i < pivotCols.length; i++) {
    const col = pivotCols[i];
    if (q[col] === 1) {
      for (let c = col; c < width; c++) q[c] ^= rows[i][c];
    }
  }
  return q.every((x) => x === 0);
}
