import type { Block } from "../types";
import { parseDaeToBlocks } from "./daeImport";

// Bundled .dae templates live under /public/templates and are generated by
// scripts/generate_templates.py from the tqec.gallery module.

export interface TemplateEntry {
  filename: string;
  name: string;
  description: string;
}

interface TemplateManifest {
  source: string;
  regenerate: string;
  templates: TemplateEntry[];
}

const MANIFEST_URL = "/templates/manifest.json";

export async function fetchTemplateManifest(): Promise<TemplateEntry[]> {
  const res = await fetch(MANIFEST_URL);
  if (!res.ok) throw new Error(`Failed to load template manifest (${res.status})`);
  const data = (await res.json()) as TemplateManifest;
  return data.templates;
}

export async function loadTemplateBlocks(filename: string): Promise<Map<string, Block>> {
  const res = await fetch(`/templates/${filename}`);
  if (!res.ok) throw new Error(`Failed to load template ${filename} (${res.status})`);
  const xml = await res.text();
  return parseDaeToBlocks(xml);
}
